-- 1️⃣ Create the table
CREATE TABLE IF NOT EXISTS shrines (
    id SERIAL PRIMARY KEY,
    shrine_name TEXT NOT NULL,
    shrine_code TEXT,
    region TEXT NOT NULL,
    challenge TEXT,
    rewards TEXT,
    done BOOLEAN DEFAULT FALSE,
    map_link TEXT
);

INSERT INTO shrines (shrine_name, region, challenge, rewards, done, map_link) VALUES
('Dah Hesho Shrine','Akkala','A Minor Test of Strength','Giant Ancient Core',0,NULL),
('Katosa Aug Shrine','Akkala','Katosa Aug Apparatus','Great Frostblade',0,NULL),
('Ke''nai Shakah Shrine','Akkala','A Modest Test of Strength','Sapphire',0,NULL),
('Ritaag Zumo Shrine','Akkala','Into the Vortex / Ritaag Zumo''s Blessing','Giant Ancient Core',0,NULL),
('Tu Ka''loh Shrine','Akkala','Trial of the Labyrinth / Lomei Labyrinth Island','Ancient Core',0,NULL),
('Tutsuwa Nima Shrine','Akkala','A Major Test of Strength / The Spring of Power','Flamespear',0,NULL),
('Ze Kasho Shrine','Akkala','Ze Kasho Apparatus','Silverscale Spear',0,NULL),
('Zuna Kai Shrine','Akkala','The Skull''s Eye / Zuna Kai''s Blessing','Flame Blade',0,NULL),

('Dah Kaso Shrine','Central Hyrule','A Minor Test of Strength','Ancient Core',0,NULL),
('Kaam Ya''tak Shrine','Central Hyrule','Trial of Power','Edge of Duality, Silver Rupee, Diamond',0,NULL),
('Katah Chuki Shrine','Central Hyrule','A Minor Test of Strength','Royal Halberd',0,NULL),
('Namika Ozz Shrine','Central Hyrule','A Modest Test of Strength','Frostspear',0,NULL),
('Noya Neha Shrine','Central Hyrule','A Minor Test of Strength','Royal Shield',0,NULL),
('Rota Ooh Shrine','Central Hyrule','Passing of the Gates','Feathered Edge',0,NULL),
('Saas Ko''sah Shrine','Central Hyrule','A Major Test of Strength','Flameblade',0,NULL),
('Wahgo Katta Shrine','Central Hyrule','Metal Connections','Amber',0,NULL),

('Bosh Kala Shrine','Dueling Peaks','The Wind Guides You','Soldier''s Claymore, Amber',0,NULL),
('Ha Dahamar Shrine','Dueling Peaks','The Water Guides','Purple Rupee',0,NULL),
('Hila Rao Shrine','Dueling Peaks','Watch Out for the Flowers / Drifting','Opal, Ice Arrows x5',0,NULL),
('Lakna Rokee Shrine','Dueling Peaks','The Stolen Heirloom / Blessing','Edge of Duality',0,NULL),
('Ree Dahee Shrine','Dueling Peaks','Timing Is Critical','Climber''s Bandana',0,NULL),
('Shee Vaneer Shrine','Dueling Peaks','Twin Memories','Eightfold Longblade',0,NULL),
('Shee Venath Shrine','Dueling Peaks','Twin Memories','Serpentine Spear',0,NULL),
('Ta''loh Naeg Shrine','Dueling Peaks','Ta''loh Naeg''s Teaching','Eightfold Longblade, Opal, Shield of the Mind''s Eye',0,NULL),
('Toto Sah Shrine','Dueling Peaks','Toto Sah Apparatus','Shield of the Mind''s Eye',0,NULL),

('Daqa Koh Shrine','Eldin','Stalled Flight','Silver Rupee',0,NULL),
('Gorae Torr Shrine','Eldin','The Gut Check Challenge / Blessing','Great Frostblade',0,NULL),
('Kayra Mah Shrine','Eldin','A Brother''s Roast / Greedy Hill','Ruby',0,NULL),
('Mo''a Keet Shrine','Eldin','Metal Makes a Path','Knight''s Broadsword',0,NULL),
('Qua Raym Shrine','Eldin','A Balanced Approach','Knight''s Claymore',0,NULL),
('Sah Dahaj Shrine','Eldin','Power of Fire','Knight''s Bow',0,NULL),
('Shae Mo''sah Shrine','Eldin','Swinging Flames','Stone Smasher, Ruby, Ice Arrows x10',0,NULL),
('Shora Hah Shrine','Eldin','Blue Flame','Giant Ancient Core, Great Flameblade, Silver Rupee',0,NULL),
('Tah Muhl Shrine','Eldin','A Landscape of a Stable / Passing the Flame','Cobble Crusher, Opal, Ruby',0,NULL),

('Kah Yah Shrine','Faron','A Fragmented Monument / Quick Thinking','Royal Claymore',0,NULL),
('Korgu Chideh Shrine','Faron','Stranded on Eventide / Blessing','Gold Rupee',0,NULL),
('Muwo Jeem Shrine','Faron','A Modest Test of Strength','Royal Bow',0,NULL),
('Qukah Nata Shrine','Faron','Song of Storms / Blessing','Rubber Tights',0,NULL),
('Shai Utoh Shrine','Faron','Halt the Tilt','Traveler''s Sword, Ancient Core',0,NULL),
('Shoda Sah Shrine','Faron','Impeccable Timing','Ice Arrows x5',0,NULL),
('Tawa Jinn Shrine','Faron','The Three Giant Brothers / Blessing','Great Thunderblade',0,NULL),
('Yah Rin Shrine','Faron','A Weighty Decision','Knight''s Broadsword, Opal',0,NULL),

('Joloo Nah Shrine','Gerudo Highlands','Test of Will / Joloo Nah Apparatus','Golden Claymore, Gerudo Spear',0,NULL),
('Keeha Yoog Shrine','Gerudo Highlands','Cliffside Etchings / Blessing','Diamond',0,NULL),
('Kema Kosassa Shrine','Gerudo Highlands','A Major Test of Strength','Silver Rupee',0,NULL),
('Kuh Takkar Shrine','Gerudo Highlands','Melting Ice Hazard','Frostblade',0,NULL),
('Sasa Kai Shrine','Gerudo Highlands','Sign of the Shadow / A Modest Test of Strength','Frostblade',0,NULL),
('Sho Dantu Shrine','Gerudo Highlands','Two Bombs','Silver Rupee',0,NULL),

('Dako Tah Shrine','Gerudo Wastelands','Electric Path','Moonlight Scimitar, Ancient Core, Silver Rupee',0,NULL),
('Daqo Chisay Shrine','Gerudo Wastelands','The Whole Picture','Thunderblade',0,NULL),
('Dila Maag Shrine','Gerudo Wastelands','South Lomei Labyrinth / Blessing','Barbarian Armor Piece',0,NULL),
('Hawa Koth Shrine','Gerudo Wastelands','The Current Solution','Ancient Core, Gold Rupee, Sapphire',0,NULL),
('Jee Noh Shrine','Gerudo Wastelands','On the Move','Opal',0,NULL),
('Kay Noh Shrine','Gerudo Wastelands','Power of Electricity','Gerudo Scimitar',0,NULL),
('Kema Zoos Shrine','Gerudo Wastelands','A Delayed Puzzle','Moonlight Scimitar',0,NULL),
('Korsh O''hu Shrine','Gerudo Wastelands','The Seven Heroines / Blessing','Flamespear',0,NULL),
('Misae Suma Shrine','Gerudo Wastelands','The Perfect Drink / Blessing','Diamond',0,NULL),
('Raqa Zunzo Shrine','Gerudo Wastelands','The Undefeated Champ / Blessing','Radiant Shield',0,NULL),
('Suma Sahma Shrine','Gerudo Wastelands','Snow Shrine','Moonlight Scimitar',0,NULL),
('Tho Kayu Shrine','Gerudo Wastelands','Blessing','Golden Bow',0,NULL),

('Daag Chokah Shrine','Great Hyrule Forest','The Lost Pilgrimage / Blessing','Ancient Core',0,NULL),
('Keo Ruug Shrine','Great Hyrule Forest','Fateful Stars','Knight''s Claymore',0,NULL),
('Ketoh Wawai Shrine','Great Hyrule Forest','Shrouded Shrine / Blessing','Ancient Core',0,NULL),
('Kuhn Sidajj Shrine','Great Hyrule Forest','Trial of Second Sight / Blessing','Giant Ancient Core',0,NULL),
('Maag Halan Shrine','Great Hyrule Forest','The Test of Wood / Blessing','Giant Ancient Core',0,NULL),
('Mirro Shaz Shrine','Great Hyrule Forest','Tempered Power','Iron Sledgehammer (x2), Giant Ancient Core',0,NULL),
('Monya Toma Shrine','Great Hyrule Forest','Drawing Parabolas','Thunderblade',0,NULL),
('Rona Kachta Shrine','Great Hyrule Forest','Blessing','Great Flameblade',0,NULL),

('Ja Baij Shrine','Great Plateau','Bomb Trial','Remote Bombs Rune, Traveler''s Claymore, Amber',0,NULL),
('Keh Namut Shrine','Great Plateau','Cryonis Trial','Cryonis Rune, Traveler''s Spear',0,NULL),
('Oman Au Shrine','Great Plateau','Magnesis Trial','Magnesis Rune, Traveler''s Bow',0,NULL),
('Owa Daim Shrine','Great Plateau','Stasis Trial','Stasis Rune, Traveler''s Shield, Iron Sledgehammer',0,NULL),

('Chaas Qeta Shrine','Hateno','Major Test of Strength','Climbing Gear',0,NULL),
('Dow Na''eh Shrine','Hateno','Three Boxes','Zora Sword, Zora Sword, Amber, Opal',0,NULL),
('Jitan Sa''mi Shrine','Hateno','The Spring of Wisdom','Frostspear',0,NULL),
('Kam Urog Shrine','Hateno','A Cursed Statue / Trial of Passage','Soldier''s Spear, Opal',0,NULL),
('Mezza Lo Shrine','Hateno','The Crowned Beast / Ancient Trifecta','Thunderblade',0,NULL),
('Myahm Agana Shrine','Hateno','Myahm Agana Apparatus','Phrenic Bow',0,NULL),
('Tahno O''ah Shrine','Hateno','Secret of the Cedars / Blessing','Climbing Boots',0,NULL),

('Dunba Taag Shrine','Hebra','Build and Release','Falcon Bow, Great Thunderblade',0,NULL),
('Gee Ha''rah Shrine','Hebra','Tandem','Diamond',0,NULL),
('Goma Asaagh Shrine','Hebra','A Major Test of Strength','Royal Claymore',0,NULL),
('Hia Miu Shrine','Hebra','A Major Test of Strength','Sapphire',0,NULL),
('Lanno Kooh Shrine','Hebra','Blessing','Gold Rupee',0,NULL),
('Maka Rah Shrine','Hebra','Steady Thy Heart','10 Bomb Arrows, Ancient Core, Diamond',0,NULL),
('Mozo Shenno Shrine','Hebra','The Bird in the Mountain / A Major Test of Strength','Diamond',0,NULL),
('Qaza Tokki Shrine','Hebra','Trial on the Cliff / Blessing','Barbarian Armor Piece',0,NULL),
('Rin Oyaa Shrine','Hebra','Directing the Wind','Ancient Core',0,NULL),
('Rok Uwog Shrine','Hebra','Power of Reach','Drillshaft',0,NULL),
('Sha Gehma Shrine','Hebra','Shift and Lock','Royal Broadsword',0,NULL),
('Shada Naw Shrine','Hebra','Red Giveaway','Great Frostblade',0,NULL),
('To Quomo Shrine','Hebra','Blessing','Royal Claymore',0,NULL),

('Ishto Soh Shrine','Lake','Bravery''s Grasp','Topaz, Ancient Core',0,NULL),
('Ka''o Makagh Shrine','Lake','Metal Doors Open the Way','Traveler''s Bow, Gold Rupee, Opal',0,NULL),
('Pumaag Nitae Shrine','Lake','A Minor Test of Strength','Boomerang',0,NULL),
('Shae Katha Shrine','Lake','The Serpent''s Jaw / Blessing','Thunderspear',0,NULL),
('Shoqa Tatone Shrine','Lake','A Modest Test of Strength','Royal Broadsword',0,NULL),
('Ya Naga Shrine','Lake','Shatter the Heavens','Eightfold Blade',0,NULL),

('Dagah Keek Shrine','Lanayru','The Ceremonial Song / Blessing','Silver Rupee',0,NULL),
('Daka Tuss Shrine','Lanayru','Sunken Scoop','Silver Longsword',0,NULL),
('Kaya Wan Shrine','Lanayru','Shields From Water','Ancient Core, Knight''s Broadsword',0,NULL),
('Kah Mael Shrine','Lanayru','Drop and Rise','Diamond',0,NULL),
('Ne''ez Yohma Shrine','Lanayru','Pushing Power','Zora Spear',0,NULL),
('Rucco Maag Shrine','Lanayru','The Five Torches','Opal, Silver Bow',0,NULL),
('Shai Yota Shrine','Lanayru','Master of the Wind / Blessing','Great Flameblade',0,NULL),
('Sheh Rata Shrine','Lanayru','Speed of Light','Opal, Giant Boomerang',0,NULL),
('Soh Kofi Shrine','Lanayru','A Minor Test of Strength','Knight''s Bow',0,NULL),

('Mijah Rokee Shrine','Ridgeland','Under a Red Moon / A Modest Test of Strength','Frostblade',0,NULL),
('Maag No''rah Shrine','Ridgeland','Blessing','Silver Rupee',0,NULL),
('Mogg Latan Shrine','Ridgeland','Synced Swing','Forest Dweller''s Spear, Forest Dweller''s Bow, Gold Rupee',0,NULL),
('Shae Loya Shrine','Ridgeland','Aim for the Moment','Topaz, Falcon Bow',0,NULL),
('Sheem Dagoze Shrine','Ridgeland','The Two Rings / Moving in Parallel','Great Thunderblade',0,NULL),
('Toh Yahsa Shrine','Ridgeland','Trial of Thunder / Buried Secrets','Rubber Armor, Opal',0,NULL),
('Zalta Wa Shrine','Ridgeland','Two Orbs to Guide You','Knight''s Bow',0,NULL),

('Akh Va''quot Shrine','Tabantha','Windmills','Ancient Core, Sapphire, Feathered Spear',0,NULL),
('Bareeda Naag Shrine','Tabantha','The Ancient Rito Song / Cannon','Falcon Bow, Diamond',0,NULL),
('Kah Okeo Shrine','Tabantha','Wind Guide','Korok Leaf, Gold Rupee, Forest Dweller''s Sword',0,NULL),
('Sha Warvo Shrine','Tabantha','Path of Hidden Flights','Purple Rupee, Knight''s Bow',0,NULL),
('Tena Ko''sah Shrine','Tabantha','A Major Test of Strength','Knight''s Halberd',0,NULL),
('Voo Lota Shrine','Tabantha','Recital at Warbler''s Nest / The Winding Route','Flameblade',0,NULL);
